# Generated by Django 4.1.3 on 2022-12-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curdapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Register", new_name="Employees",),
    ]
