# Generated by Django 4.1.3 on 2022-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curdapp", "0002_rename_register_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="Address",
            field=models.TextField(max_length=250),
        ),
    ]
